- hosts: postgres
  gather_facts: no

- hosts: ldap
  gather_facts: no

  vars_files:
    - vars.yml

  tasks:
    - name: Install convinience packages
      yum: name=vim,epel-release state=latest

    - name: Install ldap packages
      yum: name=openldap,openldap-servers-sql state=latest

    - name: Install odbc
      yum: name=unixODBC state=latest

    - name: Install Postgres Client
      yum: name=postgresql-odbc,postgresql state=latest

    - name: Add the backsql-script
      copy: src=../ldap/backsql_create.sql dest=/root/backsql_create.sql owner=root group=root mode=0664

    - name: Add the ODBC.ini
      template: src=../ldap/odbc.ini.j2 dest=/etc/odbc.ini owner=root group=root mode=0664

    - name: Add the slapd.conf
      template: src=../ldap/slapd.conf.j2 dest=/etc/openldap/slapd.conf owner=root group=root mode=0664

    - name: Create the openldap pid folder
      file: path=/usr/local/var state=directory owner=root group=root mode=0775

    - name: Add the entrypoint
      template: src=../ldap/entrypoint.sh.j2 dest=/root/entrypoint.sh owner=root group=root mode=0774
