- hosts: localhost 
  gather_facts: no

  become_user: root
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Install convinience packages
      yum: name=vim,epel-release state=latest

    - name: Install ldap packages
      yum: name=openldap,openldap-devel,openldap-servers-sql state=latest

    - name: Install python ldap
      pip: 
        name: python-ldap 

    - name: Install odbc
      yum: name=unixODBC state=latest

    - name: Install Postgres Client
      yum: name=postgresql-odbc,postgresql state=latest

    - name: Add the backsql-script
      copy: src=../ldap/backsql_create.sql dest=/root/backsql_create.sql owner=root group=root mode=0664

    - name: Add the ODBC.ini
      template: src=../ldap/odbc.ini.j2 dest=/etc/odbc.ini owner=root group=root mode=0664

    - name: Add the slapd.conf
      template: src=../ldap/slapd.conf.j2 dest=/etc/openldap/slapd.conf owner=root group=root mode=0664

    - name: Create the openldap pid folder
      file: path=/usr/local/var state=directory owner=root group=root mode=0775

    - name: Add the entrypoint
      template: src=../ldap/entrypoint.sh.j2 dest=/root/entrypoint.sh owner=root group=root mode=0774

    - name: Add the pgpass file to root user
      template: src=../ldap/pgpass.j2 dest=/root/.pgpass owner=root group=root mode=0600

    - name: Create the initial LDAP schema
      become_user: root
      become: true
      shell: psql -h {{ postgres_server }} -U {{ postgres_user }} {{ database_name }} -w < /root/backsql_create.sql

    - name: Blow away default schema
      become_user: root
      become: true
      shell: rm -rf /etc/openldap/slapd.d/*

    - name: Create initial ldap config
      become_user: root
      become: true
      shell: slaptest -f /etc/openldap/slapd.conf -F /etc/openldap/slapd.d/
    
    - name: ensure proper ldap owner
      file:
        path: /etc/openldap
        state: directory
        mode: 0700
        recurse: true
        owner: ldap
        group: ldap

    - name: start slapd
      service:
        name: slapd
        state: running
        enabled: true

    - name: bind to ldap
      ldap_auth:
        server_uri: "ldap://localhost/"
        bind_dn: "cn=root,{{ ldap_base }}"
        bind_pw: "{{ ldap_admin_password }}"
